### ISSUE TITLE
Error in loading DLL: 'zipApp.NameSpace'

### ISSUE THREAD

**Issue by neconsult** [rcdmk/aspZip#10]
Hello, i am trying to use for the first time and i got this error. Could you give me some help?
Tks

My host is locaweb.com.br

Error:
Microsoft VBScript runtime error '800a0030'
Error in loading DLL: 'zipApp.NameSpace'
/aspZip.class.asp, line 86

My Code:
<%
option explicit
Server.ScriptTimeout=9000
%>

<%
dim zip, filepath

filepath = ".\downloads\test.zip"

set zip = new aspZip

zip.OpenArquieve(filepath)

zip.Add("..\css")

zip.CloseArquieve()

set zip = nothing
%>
OK

**Comment by rcdmk** [comment]
Hi,

This was written some time ago and your host may not be on a supported version of Windows.

What is the Windows version for your server?

I can try testing it on newer versions to see if the same problem occurs to try and solve it, but I haven't touched this in a while, so it may take some time to get to a solution.

The error points out that the system zip lib is missing, what may imply a newer or older Windows version that doesn't have it or has a different name.

**Comment by neconsult** [comment]
The version of server is Windows Server 2022

**Comment by rcdmk** [comment]
I'm experimenting on Windows 11 and IIS Express and it works, so I'd expect It to also work on Windows Server 2022, since it is based of Windows 10.

Could be a specific configuration on those servers, specially if those are shared hosting.

This class relies on the native ZIP folder support in Explorer, which may only be available on UI versions of Windows Server. If that particular installation has no UI, that may be the reason.

**Comment by neconsult** [comment]
It is a shared host, and i don´t have rights to change it.

Any other idea about this or oder to Zip or compact a folder using ASP Classic?
Someone got it?

**Comment by rcdmk** [comment]
Shared hosting is very limited, indeed. That removes most of your options.

In the past, those servers used to offer some paid Classic ASP components, though. Probably not supported anymore, but it could be worth a try checking their documentation for available components, like the ones to manage uploads and image resizing.

You could also try to use the portable 7zip executable and running it with `Wscript.Shell`, but I doubt that will work on shared hosting as well.

I'll try a few code changes today and make a branch available for you to test. Maybe that will work.

As an alternative, have you considered running a .Net lib from ASP instead? If you can push .Net libs to the server, maybe you can use them through Classic ASP as well: https://stackoverflow.com/questions/3528730/create-zip-files-in-classic-asp-using-dotnetzip-or-sharpziplib

**Comment by rcdmk** [comment]
Could you please try again with the new version 0.4 that I just released.

I was able to make it work to compress and extract files on Windows 11 Home and IIS Express, which is a limited version of Windows as well.

Not guaranteed, as the missing DLL is probably due to non desktop server version.

**Comment by neconsult** [comment]
Hello Ricardo, thank you very much but still the same problem.

I updated the version and test again.
I don´t know anymore what to do.

Microsoft VBScript runtime error '800a0030'

Error in loading DLL: 'zipApp.NameSpace'

/aspZip.class.asp, line 86

This line is:
			set curArquieve = zipApp.NameSpace(m_path)

**Comment by neconsult** [comment]
on this server they have this components pre-installed
![Imagem1-1](https://github.com/rcdmk/aspZip/assets/45170226/45085d9c-7092-4494-aec6-16d6d5fdc6b3)
![Imagem3](https://github.com/rcdmk/aspZip/assets/45170226/cec47bc9-5d8d-47fb-a5a8-2df1a0113508)

**Comment by neconsult** [comment]
![Imagem3](https://github.com/rcdmk/aspZip/assets/45170226/b3f2bbc3-bcc6-42d8-afd6-74e54d4202f6)

**Comment by rcdmk** [comment]
Yeah... It looks like you are out of luck in this case. If uploading and running a portable 7zip executable doesn't work and using .Net stuff is not possible, there is nothing else I can think of at this time.

Maybe asking support to move you to another server that offers some of those can be a way around it. I've done that in the past with Locaweb and they could get me into an older server.

In your case, your best bet would be to use asp.net or PHP to so part of the work, then.

**Comment by neconsult** [comment]
Do you have some example of this in asp.net or similar windows technology?

**Comment by rcdmk** [comment]
I don't have any examples at hand, but the Stack Overflow link I shared before should be a good starting point.

**Comment by neconsult** [comment]
thanks a lot for this moment.
